### ISSUE TITLE
Fails to load in Foundry v10

### ISSUE THREAD

**Issue by illandril** [kckaiwei/TurnMarker-alt#104]
```
FoundryVTT | 2022-08-07 18:01:59 | [error] Metadata validation failed for module "turnmarker": The file "css/turnmarker.css" included by module turnmarker does not exist
Error: Metadata validation failed for module "turnmarker": The file "css/turnmarker.css" included by module turnmarker does not exist
    at PackageAssetField.initialize (REDACTED/foundryvtt/resources/app/dist/packages/package.mjs:1:1262)
    at REDACTED/foundryvtt/resources/app/common/data/fields.mjs:857:40
    at Array.map (<anonymous>)
    at SetField.initialize (REDACTED/foundryvtt/resources/app/common/data/fields.mjs:857:18)
    at SetField.initialize (REDACTED/foundryvtt/resources/app/common/data/fields.mjs:908:26)
    at Module._initialize (REDACTED/foundryvtt/resources/app/common/abstract/data.mjs:196:27)
    at Module._initialize (REDACTED/foundryvtt/resources/app/dist/packages/package.mjs:1:2903)
    at new DataModel (REDACTED/foundryvtt/resources/app/common/abstract/data.mjs:59:10)
    at new BasePackage (REDACTED/foundryvtt/resources/app/common/packages/base-package.mjs:59:5)
    at new BaseModule (REDACTED/foundryvtt/resources/app/common/packages/base-module.mjs:11:16)
```

The same issue is happening in earlier versions, it just doesn't prevent it from loading. The problem is turnmarker.less is never processed into a css file (but you aren't using anything less provides, so you could just change the extension).

**Comment by illandril** [comment]
For anyone looking for a replacement, I am in the process of creating one: https://github.com/illandril/FoundryVTT-turn-marker
It will NOT be a 1:1 match for this module, so not everyone who used TurnMarker-alt will necessarily want to use my module (and some who didn't like TurnMarker-alt might like mine).

Another alternative is [Combat Booster](https://foundryvtt.com/packages/combatbooster)
